### PR TITLE
fix compiler warnings. closes #57

### LINKED ISSUE #57: Many compile warnings
Lots of unsafe variable messages as well as unknown PosixError exception on elixir 1.3

### PR DESCRIPTION
**Pull request by smpallen99**
Clean compile now

### CODE REVIEW

**Comment by radar** [comment]
This PR looks good to me. Could we please get it merged?

**Comment by liveforeverx** [comment]
If shorter form needed, than all modifications can be rewritten as:

```elixir
args = Keyword.put_new_lazy(args, :priority, fn -> Keyword.get(options, :priority) end)
```

And it will be probably shorter and not longer, as original form without `else`...

**Comment by meh** [comment]
Yes and no, there's a much cleaner way to do it with `Enum.flat_map`, I was going to fix it myself but for some reason `mix` is segfaulting on my machine and I was too lazy to look into why that's the case.

Gonna work on it now.

**Comment by meh** [comment]
Can someone test master please?

I fixed the warnings in a clearer way but option checking also became stricter, and I can't test anything because Erlang is completely broken on my system, and fixing it will take time.

**Comment by ilasorsa** [comment]
@meh 

I cloned the repo, mix clean, mix compile, no warnings for me :)

**Comment by radar** [comment]
Could we please get a new version of this pushed to hex.pm?

**Comment by meh** [comment]
I wish, but Erlang is currently busted on my machine, it segfaults on anything using SSL.

**Pull request closed without merging**
